### PR TITLE
Added the bot emoji.

### PR DESCRIPTION
**Pull request by jedevc**
Hopefully, this will work. I haven't tested it as I haven't yet installed a copy of heim on my computer...

### CODE REVIEW

**Comment by CylonicRaider** [comment]
OK, I approve the emoji because of its cuteness. :smile:

**Comment by jedevc** [comment]
@chromakode I realize that you are busy, but will this eventually be merged? Or not?

**Comment by CylonicRaider** [comment]
@jedevc, don't even hope that would happen.

**Comment by chromakode** [comment]
Sorry, I've been focused on developing towards our general release and have fallen behind on pull requests. I'll make sure this and your other pull request get attention in the coming week.

**Comment by jedevc** [comment]
Thanks.

**Comment by chromakode** [comment]
Alright, `:bot:` now added! I redrew this one to be more recognizable at smaller sizes, but hopefully retained some of the original flavor. :D https://github.com/euphoria-io/heim/commit/fef2610a6281868a1b39bf0d39009f9755a36ef5

**Comment by jedevc** [comment]
This probably should be closed :D

**Pull request closed without merging**
