### PR TITLE
use tip, lastest version of go

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by shurcooL** [comment]
You may want to consider adding:

```
matrix:
  allow_failures:
    - go: tip
```

So that failures building on tip are considered allowed failures. That way you can still see and anticipate issues, but breaking unstable changes on tip don't trip your builds.

**Comment by bitdop** [comment]
@shurcooL suggestion made

**Comment by bitdop** [comment]
@shurcooL hmm, weird that it's mandatory as it should have been added through allow_failures, but the fix is made

**Comment by shurcooL** [comment]
You can see in the [latest Travis build](https://travis-ci.org/euphoria-io/heim/builds/76906895) for this PR that it in fact builds for both 1.4 and tip (with allowed failure). That was not the case in the [previous Travis build](https://travis-ci.org/euphoria-io/heim/builds/76904361).

LGTM.

**Comment by cpalone** [comment]
Hm, my only worry with this is that using tip as opposed to 1.5 will build go from source- increasing the amount of time before we get feedback from Travis.

**Comment by shurcooL** [comment]
I think since tip is included under `allow_failures`, it will show you results as soon as all other builds complete. So this would be just an additional signal you can check by explicitly visiting the build page.

**Comment by cpalone** [comment]
http://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing

"Now, a build will finish as soon as a job has failed, or when the only jobs left allow failures."

Looks like there is an option for that that we'd need to explicitly set.

**Comment by shurcooL** [comment]
Good find, you are right. Then it sounds like you want to add `fast_finish: true` to the config.

**Comment by shurcooL** [comment]
@cpalone, any additional thoughts?

**Comment by chromakode** [comment]
Merged: 1618b2c8ec2c7a1894ba5b6c11c14cf48086096b

Thanks!

**Pull request closed without merging**
